wandb_version: 1

algorithm:
  desc: null
  value: PPO
env_name:
  desc: null
  value: oscar
discount_factor:
  desc: null
  value: 0.6
train_timesteps:
  desc: null
  value: 1e4
random_seed:
  desc: null
  value: 777
target_device:
  desc: null
  value: pixel3
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697700825.310866
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: darwin-x86_64
